fix: make a type discrimination of the reader.result.
 When built in the html web-renderer, an error may occur:
 TypeError: Instance of 'NativeByteBuffer': type 'NativeByteBuffer' is not a subtype of type 'List<int>'.

 Therefore, we need to make a type discrimination of the reader.result.